### Site Settings ###
title               : Friedsoda
description         : >-
                      我是馒馒头
                      这里不定期分享demo和笔记 _(:з」∠)_
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : Friedsoda/fried     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU


favicon: /assets/img/favicon.ico

### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Friedsoda
  image             : /assets/img/hb.jpg
#  behance           : Friedsoda
# dribbble          : your_username
  email             : friedsoda1992@gmail.com
#  facebook          : Friedsoda
  github            : Friedsoda
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
# linkedin          : Friedsoda
#  medium            : Friedsoda
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
#  twitter           : Friedsoda
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username


### Posts ###
permalink: /blog/:title
markdown: kramdown
toc_levels: 2……4

### Collections ###
collections:
  projects:
    output: true
    permalink: /collections/:name


### Disqus ###
disqus:
  shortname: friedsoda                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: true                                # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
